Repository exercism/cairo, pull requests merged in 2024-09, with the labels that each got.

#155 ci(dependabot): change to monthly interval
  .github/dependabot.yml
Labels: x:size/tiny

#273 Add perfect-numbers
  config.json
  exercises/practice/perfect-numbers/.docs/instructions.md
  exercises/practice/perfect-numbers/.meta/config.json
  exercises/practice/perfect-numbers/.meta/example.cairo
  exercises/practice/perfect-numbers/.meta/tests.toml
  exercises/practice/perfect-numbers/Scarb.toml
  exercises/practice/perfect-numbers/src/lib.cairo
  exercises/practice/perfect-numbers/tests/perfect_numbers.cairo
Labels: x:rep/large

#275 Add nucleotide-count
  config.json
  exercises/practice/nucleotide-count/.docs/instructions.md
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/nucleotide-count/.meta/example.cairo
  exercises/practice/nucleotide-count/.meta/tests.toml
  exercises/practice/nucleotide-count/Scarb.toml
  exercises/practice/nucleotide-count/src/lib.cairo
  exercises/practice/nucleotide-count/tests/nucleotide_count.cairo
Labels: x:rep/large

#278 Add timeout to _./bin/verify-exercises_
  bin/verify-exercises
Labels: x:rep/small

#274 Add atbash-cipher
  config.json
  exercises/practice/atbash-cipher/.docs/instructions.md
  exercises/practice/atbash-cipher/.meta/config.json
  exercises/practice/atbash-cipher/.meta/example.cairo
  exercises/practice/atbash-cipher/.meta/tests.toml
  exercises/practice/atbash-cipher/Scarb.toml
  exercises/practice/atbash-cipher/src/lib.cairo
  exercises/practice/atbash-cipher/tests/atbash_cipher.cairo
Labels: x:rep/large

#280 Fix: call 'exit 1' only if test times out (fix command precedence)
  bin/verify-exercises
Labels: x:rep/tiny, x:action/fix, x:type/coding

#135 Trait concepts
  concepts/traits/.meta/config.json
  concepts/traits/about.md
  concepts/traits/introduction.md
  concepts/traits/links.json
Labels: x:rep/large

#279 Sync `protein-translation` with Canonical Data
  exercises/practice/protein-translation/.meta/example.cairo
  exercises/practice/protein-translation/src/lib.cairo
  exercises/practice/protein-translation/tests/protein_translation.cairo
Labels: x:rep/large

#284 Add `proverb`
  config.json
  exercises/practice/proverb/.docs/instructions.md
  exercises/practice/proverb/.meta/config.json
  exercises/practice/proverb/.meta/example.cairo
  exercises/practice/proverb/.meta/tests.toml
  exercises/practice/proverb/Scarb.toml
  exercises/practice/proverb/src/lib.cairo
  exercises/practice/proverb/tests/proverb.cairo
Labels: x:module/practice-exercise, x:type/content, x:rep/large, x:action/create, x:type/coding

#283 Implement `grains`
  config.json
  exercises/practice/grains/.docs/instructions.md
  exercises/practice/grains/.meta/config.json
  exercises/practice/grains/.meta/example.cairo
  exercises/practice/grains/.meta/tests.toml
  exercises/practice/grains/Scarb.toml
  exercises/practice/grains/src/lib.cairo
  exercises/practice/grains/tests/grains.cairo
Labels: x:module/practice-exercise, x:type/content, x:rep/large, x:action/create, x:type/coding
